"""
Milestone 6 — Evaluation harness.

Runs all 5 planning.md evaluation questions (plus one off-topic question that
SHOULD trigger the grounding decline) through the live system and writes the
results to eval_results.md so they can be transcribed into the README.

Run:
    python evaluate.py
Requires network access (calls the Groq API) and a GROQ_API_KEY in .env.
"""

from query import ask

# The 5 evaluation questions and their ground-truth answers, copied verbatim
# from planning.md's Evaluation Plan.
EVAL_QUESTIONS = [
    {
        "question": "What is the grading rigor like in CSE 311, and what tools do students recommend for taking notes and writing homework?",
        "expected": "Grading in CSE 311 is extremely strict and nitpicky, particularly for proofs where no steps can be implied. Students recommend using an iPad for handwritten lecture notes due to the heavy use of mathematical symbols, and utilizing LaTeX to format and write homework assignments.",
    },
    {
        "question": "How does the project workload of CSE 333 compare to CSE 351, and what is the typical format of its assignments?",
        "expected": "CSE 333 requires a significantly higher time commitment and workload than CSE 351. The course format consists of short C/C++ programming exercises due every few days alongside large, multi-week programming labs due roughly every two weeks that build toward an overall system project.",
    },
    {
        "question": "What are the primary grading and lecture characteristics of Professor Kevin Lin's upper-level courses?",
        "expected": "Professor Kevin Lin uses a highly test-heavy evaluation structure where exams dictate the majority of the final grade despite highly time-consuming projects. He utilizes a non-conventional grading rubric and runs a flipped classroom style where lectures focus on practice exam problems, requiring students to learn core concepts independently before class.",
    },
    {
        "question": "What specific strategy is recommended for an internal UW student looking to secure an undergraduate research position with a computer science professor?",
        "expected": "Students should avoid generic or cold requests. Instead, they should build a relationship by consistently attending the professor's weekly office hours, actively asking deep questions adjacent to the lecture material, and researching the professor's published papers beforehand. Once rapport is established mid-quarter, they can formally ask to join the lab.",
    },
    {
        "question": "Which advanced elective courses are considered critical for students aiming for a career in cloud-scale software engineering, and why?",
        "expected": "Distributed Systems (CSE 452) and Operating Systems (CSE 451) are considered the most career-critical electives for systems and backend engineering. They provide deep, foundational competency in low-level execution and cloud-scale architectures, which distinguishes candidates even when modern tools abstract the operating system away.",
    },
]

# Off-topic control: the documents contain nothing about this, so a correctly
# grounded system must decline rather than answer from training knowledge.
OFF_TOPIC_QUESTION = "What is the best pizza place near the UW campus?"


def _format_block(idx, question, expected, result):
    sources = ", ".join(result["sources"]) if result["sources"] else "(none)"
    return (
        f"### Question {idx}\n\n"
        f"**Question:** {question}\n\n"
        f"**Expected answer:** {expected}\n\n"
        f"**System response:** {result['answer']}\n\n"
        f"**Sources cited:** {sources}\n\n"
        f"**Accuracy judgment:** _[fill in: accurate / partially accurate / inaccurate]_\n\n"
        "---\n"
    )


def main():
    lines = ["# Evaluation Results\n", "_Generated by evaluate.py — transcribe into README.md._\n", "---\n"]

    for i, item in enumerate(EVAL_QUESTIONS, 1):
        print(f"Running question {i}/5 ...")
        result = ask(item["question"])
        lines.append(_format_block(i, item["question"], item["expected"], result))
        print(f"  -> {result['answer'][:100]}")
        print(f"  -> sources: {result['sources']}\n")

    # Off-topic decline check
    print("Running off-topic control question ...")
    off = ask(OFF_TOPIC_QUESTION)
    lines.append(
        "### Off-topic control (grounding check)\n\n"
        f"**Question:** {OFF_TOPIC_QUESTION}\n\n"
        f"**System response:** {off['answer']}\n\n"
        f"**Sources cited:** {', '.join(off['sources']) if off['sources'] else '(none)'}\n\n"
        "**Expected behavior:** System should decline "
        '("I don\'t have enough information on that.") rather than answer.\n\n'
        "---\n"
    )
    print(f"  -> {off['answer']}")

    with open("eval_results.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("\n✅ Wrote eval_results.md — open it, judge each answer, then copy into README.md.")


if __name__ == "__main__":
    main()